esphome:
  name: aq--sen66
  friendly_name: AQ - SEN66 

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yourkeyhere"

ota:
  - platform: esphome
    password: "yourotahere"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aq--Sen66 Fallback Hotspot"
    password: "fallbackpass"

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

external_components:
  - source:
      type: git
      url: https://github.com/tuct/esphome-projects
      ref: main
    components: [sen6x]

captive_portal:

binary_sensor:

sensor:
  - platform: sen6x
    id: sen54
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: pm10
      accuracy_decimals: 1

    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: pm25
      accuracy_decimals: 1

    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: pm40
      accuracy_decimals: 1
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: pm100
      accuracy_decimals: 1
    nox:
      name: "NOX"
      id: nox
      accuracy_decimals: 1
    co2:
      name: "CO2"
      id: co2
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
      id: temperature_top
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
      id: humidity
    voc:
      name: "VOC"
      id: voc
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
#      temperature_compensation:
#        offset: 0
#        normalized_offset_slope: 0
#        time_constant: 0
#        slot: 0
#      temperature_acceleration:
#        k: 0
#        p: 0
#        t1: 0
#        t2: 0
    store_baseline: true
    update_interval: 15s
